name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init \
          -backend-config="bucket=naveen-1812001-terraform-state-bucket" \
          -backend-config="key=global/s3/terraform.tfstate" \
          -backend-config="region=ap-south-1"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="infra/terraform.tfvars"

