name: Destroy Infrastructure

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init with S3 Backend
        run: |
          cd infra
          terraform init \
            -backend-config="bucket=naveen-1812001-terraform-state-bucket" \
            -backend-config="key=global/s3/terraform.tfstate" \
            -backend-config="region=ap-south-1" \
            -migrate-state -force-copy

      - name: Terraform Destroy
        run: |
          cd infra
          terraform destroy -auto-approve -var-file="terraform.tfvars"
